### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by toidicakhia** [toidicakhia/xmlparser#1]
- [x] Convert all to Java
- [x] Add attribute CURD
- [x] Fix indent node
